### ISSUE TITLE
can you provide vs2015 version?

### ISSUE THREAD

**Issue by kcferguson1** [OfficeDev/O365API-PopulateSampleData#1]

**Comment by jamescro** [comment]
Hello. Going forward we've concentrated our resources on creating samples that use Microsoft Graph. You can see those samples here: 
https://github.com/microsoftgraph?utf8=%E2%9C%93&q=sample

The UWP, ASP.NET, and Xamarin Microsoft Graph samples all work with VS 2015. 

Please let us know if you need guidance on Microsoft Graph operations that aren't covered in those samples.
